name: DevContainer Prebuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  packages: write

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer:latest
          push: always
          subFolder: .devcontainer
          noCache: false

      - name: Tag latest
        run: |
          docker pull ghcr.io/${{ github.repository }}/devcontainer:latest
          echo "Devcontainer prebuild image available at ghcr.io/${{ github.repository }}/devcontainer:latest"

