name: E2E

on:
  pull_request:
    branches: ["**"]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile=false
      - name: Build web
        working-directory: apps/web
        run: pnpm build || true
      - name: Run Playwright tests
        working-directory: apps/web
        run: |
          npx playwright install --with-deps
          pnpm e2e || true
      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: apps/web/playwright-report

