name: Preview

on:
  pull_request:
    branches: ["**"]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile=false
      - name: Build web
        working-directory: apps/web
        run: pnpm build || true
      - name: Preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-preview
          path: apps/web/build

